baseURL = ""
title = "Amish K. Naidu"
theme = "manis-fork"

# Copyright notice. Note: You can use HTML tag here
copyright = "&copy; 2019 Amish K. Naidu"
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 10

# Edit this if you want to translate your blog
defaultContentLanguage = "en"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
#pygmentsUseClasses = true

[taxonomies]
	tag = "tags"

[params]
	# If false, use minified CSS (ui.min.css)
	debugCSS = true
	# Custom CSS
	customCSS = []

	# Site meta description
	description = "Amish Naidu's homepage. Find his projects and blog here"
	# Site's Tagline (Subtitle or Keyword)
	tagline = "Turning coffee into code"
	# If true give attribution to this theme
	themeAttrib = false
	# URL to license file, can be outside of your domain

	# Configure which section for Latest Posts
	postSection = "blog"
	# Configure which section for Latest Works
	workSection = "projects"

	# 404 Configuration
	head404 = "Sorry, I can't find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	# Color of your website's accent
	colorTheme = "#8661C1"
        altColor = "#fff"
	# Maximum number of item in Latest Posts or Works
	latestCount = 3
	# Path to site's favicon image
	faviconImg = ""
	# Date format in item list
	dateFmt = "Jan 02, 2006"

	# Social Links
	email = "amhndu@gmail.com"
	github = "https://github.com/amhndu/"
        linkedIn = "https://www.linkedin.com/in/amish-naidu/"

        googleVerification = "-NGNp__dGrBzLzPX58fes-_QfgVl3athbCA73hpr290"
